version: "3.9"

services:
  redis:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - "6379:6379"
  db_develop:
    container_name: mariadb
    image: mariadb:10.2
    restart: on-failure
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TestDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: "America/Sao_Paulo"
    ports:
      - 3306:3306
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./:/code
      - ./static/:/static
    ports:
      - 8000:8000
    depends_on:
      - db_develop
